// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8kLRyvVzqfwgOX7x5Em05bTQ_our3TG4',
    appId: '1:117649874370:web:8f30df01f515339b338a5b',
    messagingSenderId: '117649874370',
    projectId: 'kppp-320ac',
    authDomain: 'kppp-320ac.firebaseapp.com',
    storageBucket: 'kppp-320ac.firebasestorage.app',
    measurementId: 'G-B4JECVFGZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5tbDp7xa4YVGLBXMdeC5hAUAO5ARg9cc',
    appId: '1:117649874370:android:624077d60cace08f338a5b',
    messagingSenderId: '117649874370',
    projectId: 'kppp-320ac',
    storageBucket: 'kppp-320ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3KKh5BgBYDJyuVyOQy2B72RwAv_sSDNE',
    appId: '1:117649874370:ios:76013bf0f0ab7b90338a5b',
    messagingSenderId: '117649874370',
    projectId: 'kppp-320ac',
    storageBucket: 'kppp-320ac.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3KKh5BgBYDJyuVyOQy2B72RwAv_sSDNE',
    appId: '1:117649874370:ios:76013bf0f0ab7b90338a5b',
    messagingSenderId: '117649874370',
    projectId: 'kppp-320ac',
    storageBucket: 'kppp-320ac.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8kLRyvVzqfwgOX7x5Em05bTQ_our3TG4',
    appId: '1:117649874370:web:7d831d896d8f2df8338a5b',
    messagingSenderId: '117649874370',
    projectId: 'kppp-320ac',
    authDomain: 'kppp-320ac.firebaseapp.com',
    storageBucket: 'kppp-320ac.firebasestorage.app',
    measurementId: 'G-1QMH7HBWJP',
  );
}
