// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy0PUFdFk19Hb7zQ3jLCzpRMsZRvxIQgc',
    appId: '1:839516810754:web:265f602e4d0e50655ac11b',
    messagingSenderId: '839516810754',
    projectId: 'project-kp-7223b',
    authDomain: 'project-kp-7223b.firebaseapp.com',
    storageBucket: 'project-kp-7223b.firebasestorage.app',
    measurementId: 'G-EC9GYN6BZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRk8neCuHko-iDH9zPutXfx6tP6hm5ryA',
    appId: '1:839516810754:android:4868418e5986771a5ac11b',
    messagingSenderId: '839516810754',
    projectId: 'project-kp-7223b',
    storageBucket: 'project-kp-7223b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPCDlms8zF2TiV8gsQbvab8MgdujxXQDk',
    appId: '1:839516810754:ios:1d562501106cc3415ac11b',
    messagingSenderId: '839516810754',
    projectId: 'project-kp-7223b',
    storageBucket: 'project-kp-7223b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPCDlms8zF2TiV8gsQbvab8MgdujxXQDk',
    appId: '1:839516810754:ios:1d562501106cc3415ac11b',
    messagingSenderId: '839516810754',
    projectId: 'project-kp-7223b',
    storageBucket: 'project-kp-7223b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy0PUFdFk19Hb7zQ3jLCzpRMsZRvxIQgc',
    appId: '1:839516810754:web:c2a9616f9055e9115ac11b',
    messagingSenderId: '839516810754',
    projectId: 'project-kp-7223b',
    authDomain: 'project-kp-7223b.firebaseapp.com',
    storageBucket: 'project-kp-7223b.firebasestorage.app',
    measurementId: 'G-XDHKLKBGZY',
  );
}
